# App port mapping
server.port=8081

# MongoDB Native connection String
spring.data.mongodb.uri=mongodb://localhost:27017/library_db

# Security Token Key Configuration (Must be minimum 256 bits long)
jwt.secret=9a4f2c8d3e1b7f6a5c4d3e2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a21

# Token Valid Duration (24 Hours in milliseconds)
jwt.expiration=86400000

# Prevent CORS Blockage from React Frontend local address
cors.allowed-origins=http://localhost:5173